# Generated by Django 3.2 on 2021-07-16 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='benja/videos/')),
                ('week', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foto',
            name='url',
        ),
        migrations.AddField(
            model_name='foto',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='week',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
