# Generated by Django 3.2 on 2021-07-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benja', '0002_auto_20210716_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='fecha',
        ),
    ]
