# Generated by Django 3.2 on 2021-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benja', '0003_auto_20210716_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='fecha',
            field=models.DateField(),
        ),
    ]
